sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
script: npm run ci
os:
  - linux
  - osx
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=785180885da0881a7e866929d640ef518201660357c2a4b1093ad69abf532265